{% set name = "paradoc" %}
{% set version = "0.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Krande/paradoc/archive/v{{ version }}.tar.gz
  sha256: b82ee4c9bc990e339f3341559dd9bd464efb3cf3c7105af5d8ef35920a0b03d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - paradoc=paradoc.cli_app:app

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pandoc 3.1.2
    - pandoc-crossref 0.3.16
    - pypandoc 1.12
    - python-docx
    - docxcompose
    - numpy
    - pandas
    - openpyxl
    - tabulate
    - svgwrite
    - pytexit
    - typer
    - __unix  # [unix]
    - __win   # [win]
    - pywin32  # [win]
test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest

about:
  home: https://github.com/krande/paradoc
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A Python library for Parametric Documentation"


extra:
  recipe-maintainers:
    - Krande
